### ISSUE TITLE
Some documentation please

### ISSUE THREAD

**Issue by n3storm** [berryhijwegen/Rummikub-python#1]
I know flask but I can't imagine how you plan to run application. What is your idea about running this?
Also a requirements.txt file would be nice.

Thanks

**Comment by berryhijwegen** [comment]
Hi Néstor, 
This project is a work in progress. 
You can run this project by running the app.py file.

It works with socketIO. This Flask app only contains the backend. The frontend is another repository.

**Comment by n3storm** [comment]
Thank you very much :)
